#!/bin/bash

cd /admin/iscan

. functions
dblog dowork "Starting dowork"

penable=`cat config | grep ProcEnable | gawk -F= '{ print $2 }'`

if [ $penable -eq 0 ]; then
  echo "Disabled"
  exit 3
fi

if [ -f /tmp/dowork ]; then
  echo "Already running!"
  exit 2
else
  touch /tmp/dowork
fi

cd /admin/iscan

bash randadd &
bash filladdr &
bash scanadd &
bash procscan &
bash hostwork &
bash proxycheck &
bash cleanaddrdir &

rm -rf /tmp/dowork
