#!/bin/bash

cd /admin/iscan

. functions

if [ -f /tmp/dowork ]; then
  echo "Already running!"
  exit 2
else
  touch /tmp/dowork
fi

cd /admin/iscan

bash randadd &
bash filladdr &
bash scanadd &
bash procscan &
# bash hostwork &

rm -rf /tmp/dowork
