#!/bin/bash

cd /admin/iscan

. functions

runlimit=`echo "select vfield from vars where vname='filladdrrun'" | $MYSQLQ`

for i in `echo "select addid from address where ipaddr is null and status=0 limit $runlimit" | $MYSQLQ`; do
  oct1=`echo "select oct1 from address where addid='$i'" | $MYSQLQ`
  oct2=`echo "select oct2 from address where addid='$i'" | $MYSQLQ`
  oct3=`echo "select oct3 from address where addid='$i'" | $MYSQLQ`
  oct4=`echo "select oct4 from address where addid='$i'" | $MYSQLQ`

  address="$oct1.$oct2.$oct3.$oct4"
  echo "update address set ipaddr='$address',status=1 where addid='$i'" | $MYSQLQ

done

funavgtime $processname
funproctime filladdrrun

funstop $processname
