#!/bin/bash

MYSQLQ="mysql -Dinternetscan -s"
cdate=`date +%F`

runfile='/tmp/filladdr'

if [ -f $runfile ]; then
  exit 2
else
  touch $runfile
fi


for i in `echo "select addid from address where ipaddr is null and status=0" | $MYSQLQ`; do
  oct1=`echo "select oct1 from address where addid='$i'" | $MYSQLQ`
  oct2=`echo "select oct2 from address where addid='$i'" | $MYSQLQ`
  oct3=`echo "select oct3 from address where addid='$i'" | $MYSQLQ`
  oct4=`echo "select oct4 from address where addid='$i'" | $MYSQLQ`

  address="$oct1.$oct2.$oct3.$oct4"
  echo "update address set ipaddr='$address',status=1 where addid='$i'" | $MYSQLQ

done

rm -rf $runfile
