#!/bin/bash

cd /admin/iscan

. functions

runlimit=`cat config | grep AddressWorkRun | gawk -F= '{ print $2 }'`

chkmkdir /tmp/xml

for i in `echo "select addid from address where status=3 and updown=1 limit $runlimit" | $MYSQLQ`; do
  ipaddr=`echo "select ipaddr from address where addid='$i'" | $MYSQLQ`
  if [ ! -f /tmp/xml/$ipaddr ]; then
    nmap --host-timeout 30 -oX /tmp/xml/$ipaddr $ipaddr
  fi
  for f in `cat /tmp/xml/$ipaddr | grep "port protocol" | gawk -F\" '{ print $4 }'`; do
    chtime=`date +%s`
    echo "insert into ports set addid='$i',port='$f',chtime='$chtime'" | $MYSQLQ
  done
  echo "update address set status=4 where addid='$i'" | $MYSQLQ
done

funstop $processname
