#!/bin/bash

cd /admin/iscan

. functions

echo "Null addresses: `echo "select count(*) from address where ipaddr is null" | $MYSQLQ`"
echo "Waiting to be scanned: `echo "select count(*) from address where status=1" | $MYSQLQ`"
echo "Waiting to be processed: `echo "select count(*) from address where status=2" | $MYSQLQ`"
echo "Hosts found: `echo "select count(*) from address where status>2 and updown=1" | $MYSQLQ`"
echo "Ports count: `echo "select count(*) from ports" | $MYSQLQ`"
