#!/bin/bash

MYSQLQ="mysql -Dinternetscan -s"
cdate=`date +%F`
runfile='/tmp/procscan'

if [ -f $runfile ]; then
  exit 2
else
  touch $runfile
fi

for i in `echo "select addid from address where status=2 and updown is null" | $MYSQLQ`; do
  ipaddr=`echo "select ipaddr from address where addid='$i'" | $MYSQLQ`
  if [ -f address/$ipaddr ]; then

    upstat=`cat address/$ipaddr | grep "Status: Up" | wc -l`

    if [ $upstat -eq 1 ]; then
      echo "update address set updown=1 where addid='$i'" | $MYSQLQ
    else
      echo "update address set updown=0 where addid='$i'" | $MYSQLQ
    fi

#    echo "$i $ipaddr"
  fi
done

rm -rf $runfile
