#!/bin/bash

cd /admin/iscan

. functions

ctime=`date +%s`

for i in `echo "select ipaddr from address where status=2 limit $runlimit" | $MYSQLQ`; do
  if [ -f address/$i ]; then

    upstat=`cat address/$i | grep "Status: Up" | wc -l`

    if [ $upstat -eq 1 ]; then
      echo "update address set updown=1,status=3,utime='$ctime' where ipaddr='$i'" | $MYSQLQ
    else
      echo "update address set updown=0,status=3,utime='$ctime' where ipaddr='$i'" | $MYSQLQ
    fi
  fi
done

funstop $processname
