#!/bin/bash

cd /admin/iscan

. functions

funstart procscan

runfile='/tmp/procscan'

if [ -f $runfile ]; then
  exit 2
else
  touch $runfile
fi

ctime=`date +%s`

for i in `echo "select addid from address where status=2" | $MYSQLQ`; do
  ipaddr=`echo "select ipaddr from address where addid='$i'" | $MYSQLQ`
  if [ -f address/$ipaddr ]; then

    upstat=`cat address/$ipaddr | grep "Status: Up" | wc -l`

    if [ $upstat -eq 1 ]; then
      echo "update address set updown=1,status=3,utime='$ctime' where addid='$i'" | $MYSQLQ
#      echo "$i $ipaddr $upstat 3"
    else
      echo "update address set updown=0,status=3,utime='$ctime' where addid='$i'" | $MYSQLQ
#      echo "$i $ipaddr $upstat 3"
    fi
  fi
done

funstop procscan

rm -rf $runfile
