#!/bin/bash

cd /admin/iscan

. functions

for cport in `echo "select vfield from vars where vname='proxy'" | $MYSQLR`; do

  for i in `echo "select poid from ports where port='$cport' and status=0 limit $runlimit" | $MYSQLR`; do
    ipaddr=`echo "select ipaddr from ports where poid='$i'" | $MYSQLR`
    pcheck="http://$ipaddr:$cport"

    presult=`case "$(curl -s -x $pcheck --max-time 2 -I http://google.com | sed 's/^[^ ]*  *\([0-9]\).*/\1/; 1q')" in
    [23]) echo "1";;
    5) echo "2";;
    *) echo "0";;
    esac`

    if [ $presult -eq 1 ]; then
      echo "update ports set status=1 where poid='$i' and ipaddr='$ipaddr'" | $MYSQLQ
      echo "insert into service set ipaddr='$ipaddr',poid='$i',service='proxy'" | $MYSQLQ
    elif [ $presult -eq 0 ]; then
      echo "update ports set status=3 where poid='$i' and ipaddr='$ipaddr'" | $MYSQLQ
    elif [ $presult -eq 2 ]; then
      echo "update ports set status=2 where poid='$i' and ipaddr='$ipaddr'" | $MYSQLQ
    fi

  done
done

funstop $processname
