#!/bin/bash

cd /admin/iscan

. functions

lcount=0
while [ $lcount -lt $runlimit ]; do
  ipaddr="4.`shuf -i1-255 -n1`.`shuf -i1-255 -n1`.`shuf -i1-255 -n1`"
  echo "insert ignore into address set ipaddr='$ipaddr',adddate='$cdate',status=1" | $MYSQLQ
  dblog randadd "Added $ipaddr"
  lcount=`echo "$lcount + 1" | bc`
done

lcount=0
while [ $lcount -lt $runlimit ]; do
  ipaddr="107.`shuf -i1-255 -n1`.`shuf -i1-255 -n1`.`shuf -i1-255 -n1`"
  echo "insert ignore into address set ipaddr='$ipaddr',adddate='$cdate',status=1" | $MYSQLQ
  dblog randadd "Added $ipaddr"
  lcount=`echo "$lcount + 1" | bc`
done

lcount=0
while [ $lcount -lt $runlimit ]; do
  ipaddr="`shuf -i1-255 -n1`.`shuf -i1-255 -n1`.`shuf -i1-255 -n1`.`shuf -i1-255 -n1`"
  echo "insert ignore into address set ipaddr='$ipaddr',adddate='$cdate',status=1" | $MYSQLQ
  dblog randadd "Added $ipaddr"
  lcount=`echo "$lcount + 1" | bc`
done

echo "delete from address where ipaddr like '10.%'" | $MYSQLQ
echo "delete from address where ipaddr like '172.16%'" | $MYSQLQ
echo "delete from address where ipaddr like '172.17%'" | $MYSQLQ
echo "delete from address where ipaddr like '172.18%'" | $MYSQLQ
echo "delete from address where ipaddr like '172.19%'" | $MYSQLQ
echo "delete from address where ipaddr like '172.2%'" | $MYSQLQ
echo "delete from address where ipaddr like '172.30%'" | $MYSQLQ
echo "delete from address where ipaddr like '172.31%'" | $MYSQLQ
echo "delete from address where ipaddr like '192.16%'" | $MYSQLQ

funstop $processname
