#!/bin/bash

cd /admin/iscan
. functions

ctime=`date +%s`
ctime=`echo "$ctime - 604800" | bc`

for i in `echo "select addid from address where utime<$ctime and status=4 limit 1" | $MYSQLQ`; do
  ipaddr=`echo "select ipaddr from address where addid='$i'" | $MYSQLQ`
  resethost $ipaddr
#  echo "$i `date +%s` $ctime $ipaddr"
done

funstop $processname
