#!/bin/bash

cd /admin/iscan

. functions

addrdir=`cat config | grep FileAddrDir | gawk -F= '{ print $2 }'`

for i in `echo "select ipaddr from address where status=1 limit $runlimit" | $MYSQLQ`; do
  nmap --host-timeout 15 -sn "$i" -oG address/$i
  echo "update address set status=2 where ipaddr='$i'" | $MYSQLQ
done

funstop $processname
